server:
  port: 9003

spring:
  application:
    name: dispatcher-service
  cloud:
    function:
      # definition of the function managed by Spring Cloud Function.
      # this property lets you declare which functions you want Spring Cloud Function to manage and integrate, resulting in a specific data flow.
      definition: pack|label
