apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/sanjayrawat1/bookshop/order-service/k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: order-config

images:
- name: order-service
  newName: ghcr.io/sanjayrawat1/order-service
  newTag: latest

replicas:
- count: 2
  name: order-service
