# Build
custom_build(
    # name of the container image
    ref = 'dispatcher-service',
    # command to build the container image
    command = './gradlew bootBuildImage --imageName $EXPECTED_REF',
    # files to watch that trigger a new build
    deps = ['build.gradle.kt', 'src']
)
# Deploy
k8s_yaml(
    ['k8s/deployment.yml', 'k8s/service.yml']
)

# Manage
k8s_resource(
    'dispatcher-service', port_forwards=['9002']
)
