apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Uses the manifests in your Catalog Service repo on GitHub as the base for further customizations
  # The git commit hash (sha) identifying your latest release candidate
  - github.com/sanjayrawat1/bookshop/catalog-service/k8s?ref=278ea44c59f9b1b6732991b1612624b40dca9547

# Section containing the list of patches to apply to the base manifests according to the strategic merge strategy
patchesStrategicMerge:
  # The patch for customizing the environment variables passed to the Catalog Service container
  - patch-env.yml
  - patch-volumes.yml

configMapGenerator:
  # The same ConfigMap name used in the base Kustomization
  - name: catalog-config
    # Merges this ConfigMap with the one defined in the base Kustomization
    behavior: merge
    files:
      # The additional property file added to the ConfigMap
      - application-prod.yml

images:
  - name: catalog-service
    # The new image name for the container (with your GitHub username in lowercase)
    newName: ghcr.io/sanjayrawat1/catalog-service
    # The new tag for the container (with your release candidate's unique identifier)
    newTag: 278ea44c59f9b1b6732991b1612624b40dca9547
