apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Uses the manifests in your Catalog Service repo on GitHub as the base for further customizations
  # The git commit hash (sha) identifying your latest release candidate
  - github.com/sanjayrawat1/bookshop/catalog-service/k8s?ref=278ea44c59f9b1b6732991b1612624b40dca9547
