apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9002
          env:
            - name: BOOKSHOP_CATALOG_SERVICE_URI
              value: http://catalog-service
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://bookshop-postgres/bookshop_order
            - name: SPRING_FLYWAY_URL
              value: jdbc:postgresql://bookshop-postgres/bookshop_order
            - name: SPRING_RABBITMQ_HOST
              value: bookshop-rabbitmq
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://bookshop-keycloak/realms/Bookshop
