apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /management/prometheus
        prometheus.io/port: "9002"
    spec:
      containers:
        - name: order-service
          image: order-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9002
          env:
            - name: BOOKSHOP_CATALOG_SERVICE_URI
              value: http://catalog-service
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://bookshop-postgres/bookshop_order
            - name: SPRING_FLYWAY_URL
              value: jdbc:postgresql://bookshop-postgres/bookshop_order
            - name: SPRING_RABBITMQ_HOST
              value: bookshop-rabbitmq
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://bookshop-keycloak/realms/Bookshop
          # configuration for the liveness probe.
          livenessProbe:
            # uses and HTTP GET request to get the liveness state.
            httpGet:
              # the endpoint to call for the liveness state.
              path: /management/health/liveness
              # the port to use to fetch the liveness state.
              port: 9002
            # and initial delay before starting checking the liveness state.
            initialDelaySeconds: 10
            # the frequency for checking the liveness state.
            periodSeconds: 5
          # configuration for the readiness probe.
          readinessProbe:
            httpGet:
              path: /management/health/readiness
              port: 9002
            initialDelaySeconds: 5
            periodSeconds: 15
