server:
  port: 9000
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

#logging:
#  level:
#    io.github.resilience4j: DEBUG

spring:
  application:
    name: edge-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
        pool:
          # type of connection pool (elastic, fixed, or disabled)
          type: elastic
          # idle time after which the communication channel will be closed
          max-idle-time: 15s
          # time after which communication channel will be closed
          max-life-time: 60s
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              # Number of tokens dripped in the bucket each second
              replenish-rate: 10
              # Allows request bursts of up to 20 requests, when a spike occurs, up to 20 requests are allowed per second.
              # Since replenish rate is lower than the burst capacity, subsequent burst are not allowed.
              # If two spikes happen sequentially, only the first one will succeed, while the second one will result in some request being
              # dropped with an HTTP 429 - Too Many Requests response.
              burst-capacity: 20
              # How many tokens a request costs
              requested-token: 1
        - name: Retry
          args:
            retries: 3
            method: GET
            series: SERVER_ERROR
            exceptions: java.io.IOException, java.util.concurrent.TimeoutException
            backoff:
              firstBackoff: 50ms
              maxBackoff: 500ms
              factor: 2
              basedOnPreviousValue: false
      routes:
        - id: catalog-route
          uri: ${CATALOG_SERVICE_URL:http://localhost:9001}/books
          predicates:
            - Path=/books/**
          filters:
            # name of the filter, you can choose to apply it to specific routes or define it as a default filter, like Retry filter
            - name: CircuitBreaker
              args:
                # name of the circuit breaker
                name: catalogCircuitBreaker
                # forwards request to this URI when the circuit is open
                fallbackUri: forward:/catalog-fallback
        - id: order-route
          uri: ${ORDER_SERVICE_URL:http://localhost:9002}/orders
          predicates:
            - Path=/orders/**
          filters:
            - name: CircuitBreaker
              # no fallback is defined for this circuit breaker
              args:
                name: orderCircuitBreaker
  redis:
    host: localhost
    port: 6379
    # time limit for a connection to be established
    connect-timeout: 2s
    # time limit for a response to be received
    timeout: 1s

resilience4j:
  circuitbreaker:
    configs:
      # default configuration bean for all circuit breakers
      default:
        # the size of the sliding window used to record the outcome of calls when the circuit is closed
        sliding-window-size: 20
        # number of permitted calls when the circuit is half open
        permitted-number-of-calls-in-half-open-state: 5
        # when the failure rate is above the threshold, the circuit becomes open
        failure-rate-threshold: 50
        # waiting time before moving from open to half-open (ms)
        wait-duration-in-open-state: 15000
  timelimiter:
    configs:
      # default configuration bean for all time limiters
      default:
        # configures a timeout (seconds), this timeout config will take precedence over the response timeout we define for netty HTTP client
        # using the property -> spring.cloud.gateway.httpclient.response-timeout
        timeout-duration: 5s
