version: "3.8"
services:
  catalog-service:
    depends_on:
      - bookshop-postgres
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - "9001:9001"
    environment:
      #A Paketo Buildpacks environment variable to configure the number of threads for memory calculation.
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bookshop-postgres:5432/catalog
      - SPRING_PROFILES_ACTIVE=test-data

  bookshop-postgres:
    image: "postgres:14.2"
    container_name: "bookshop-postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=catalog
