version: "3.8"
services:

  # Applications

  catalog-service:
    depends_on:
      - bookshop-postgres
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - "9001:9001"
      # The port where the JVM will listen for debug connections
      - "8001:8001"
    environment:
      # A Paketo Buildpacks environment variable to configure the number of threads for memory calculation.
      - BPL_JVM_THREAD_COUNT=50
      # Activate the JVM configuration for accepting debug connections provided by Buildpacks..
      - BPL_DEBUG_ENABLED=true
      # Debug connections are accepted via a socket on port 8001 provided by Buildpacks.
      - BPL_DEBUG_PORT=8001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bookshop-postgres:5432/bookshop_catalog
      - SPRING_PROFILES_ACTIVE=test-data

  order-service:
    depends_on:
      - bookshop-postgres
    image: order-service
    container_name: order-service
    ports:
      - "9002:9002"
      - "8002:8002"
    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
      - BOOKSHOP_CATALOG_SERVICE_URI=http://catalog-service:9001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_R2DBC_URL=r2dbc:postgresql://bookshop-postgres:5432/bookshop_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://bookshop-postgres:5432/bookshop_order

  edge-service:
    depends_on:
      - bookshop-redis
    image: edge-service
    container_name: edge-service
    ports:
      - "9000:9000"
      - "8000:8000"
    environment:
      # Buildpacks environment variable to enable debug through a socket on port 8000
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8000
      - CATALOG_SERVICE_URL=http://catalog-service:9001
      - ORDER_SERVICE_URL=http://order-service:9002
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_REDIS_HOST=bookshop-redis

  config-service:
    image: "config-service"
    container_name: "config-service"
    ports:
      - "8888:8888"
      # The port where the JVM will listen for debug connections.
      - "9888:9888"
    environment:
      # Buildpacks environment variable to configure the number of threads in memory calculation.
      - BPL_JVM_THREAD_COUNT=50
      # Buildpacks environment variable to enable debug through a socket on port 9888.
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9888

  # Backing Services

  bookshop-postgres:
    image: "postgres:14.2"
    container_name: "bookshop-postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      # No value is defined for POSTGRES_DB anymore.
    volumes:
      # Mounts the initialization SQL script to the container as a volume.
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  bookshop-redis:
    image: "redis:7.0"
    container_name: "bookshop-redis"
    ports:
      - "6379:6379"
