# Build
custom_build(
    # name of the container image
    ref = 'order-service',
    # command to build the container image
    command = './gradlew bootBuildImage --imageName $EXPECTED_REF',
    # files to watch that trigger a new build
    deps = ['build.gradle.kt', 'src']
)
# Deploy
k8s_yaml(
    kustomize('k8s')
)

# Manage
k8s_resource(
    'order-service', port_forwards=['9002']
)
