server:
  port: 9002
  shutdown: graceful
  netty:
    # how long to wait for a TCP connection to be established with the server.
    connection-timeout: 2s
    # how long to wait before closing a TCP connection if no data is transferred.
    idle-timeout: 15s

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

info:
  system: Bookshop

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: bindings, configprops, env, flyway, functions, health, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      # Adds a Micrometer common tag with the application name. This results in a Prometheus label being applied to all metrics.
      application: ${spring.application.name}

spring:
  application:
    name: order-service
  output:
    ansi:
      console-available: true
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/bookshop_order
    pool:
      # the maximum time to wait to get a connection from the pool
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/bookshop_order
  config:
    # Imports configuration data from a config server when available.
    import: "optional:configserver:"
  cloud:
    config:
      # The URL of the config server.
      uri: http://localhost:8888
      # Timeout on waiting to connect to the config server (ms).
      request-connect-timeout: 5000 # 5s
      # Timeout on waiting to read configuration data from the config server (ms).
      request-read-timeout: 5000 # 5s
      # Makes a failure to connect to the config server fatal.
      fail-fast: false # In production, set to true
      retry:
        # Maximum number of attempts.
        max-attempts: 6
        # Initial retry interval for backoff (ms).
        initial-interval: 1000 # 1s
        # Maximum retry interval for backoff (ms).
        max-interval: 2000 # 2s
        # Multiplier to compute the next interval.
        multiplier: 1.1
    function:
      # definition of the function managed by the Spring Cloud Function
      definition: dispatchOrder
    stream:
      bindings:
        # the input binding
        dispatchOrder-in-0:
          # the actual name at the broker that the binder binds to (the exchange in RabbitMQ)
          destination: order-dispatched
          # the consumer group interested in the destination
          group: ${spring.application.name}
        # output binding created and managed by StreamBridge
        acceptOrder-out-0:
          # the actual name at the broker that the binder binds to (the exchange in RabbitMQ)
          destination: order-accepted
      # RabbitMQ specific configuration for the Spring Cloud Stream bindings
      rabbit:
        bindings:
          # configure the output binding to be transactional
          acceptOrder-out-0:
            producer:
              # make the acceptOrder-out-0 binding transactional
              transacted: true
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s
  security:
    oauth2:
      resource-server:
        # OAuth2 doesn't enforce a data format for Access Tokens, so we must be explicit about our choice. In this case, we want to use JWT.
        jwt:
          issuer-uri: http://localhost:8080/realms/Bookshop

bookshop:
  greeting: Welcome to the local book order!
  catalog-service-uri: "http://localhost:9001"
