apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-service
  labels:
    app: dispatcher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher-service
  template:
    metadata:
      labels:
        app: dispatcher-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /management/prometheus
        prometheus.io/port: "9003"
    spec:
      containers:
        - name: dispatcher-service
          image: dispatcher-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9003
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: SPRING_RABBITMQ_HOST
              value: polar-rabbitmq
          # configuration for the liveness probe.
          livenessProbe:
            # uses and HTTP GET request to get the liveness state.
            httpGet:
              # the endpoint to call for the liveness state.
              path: /management/health/liveness
              # the port to use to fetch the liveness state.
              port: 9003
            # and initial delay before starting checking the liveness state.
            initialDelaySeconds: 10
            # the frequency for checking the liveness state.
            periodSeconds: 5
          # configuration for the readiness probe.
          readinessProbe:
            httpGet:
              path: /management/health/readiness
              port: 9003
            initialDelaySeconds: 5
            periodSeconds: 15
