apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  # how many pod replicas should be deployed.
  replicas: 1
  # defines the labels used to select the Pods to be scaled.
  selector:
    matchLabels:
      app: catalog-service
  # the template for creating a Pod.
  template:
    metadata:
      # labels attached to the Pod object. they should match the ones used as selectors.
      labels:
        app: catalog-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /management/prometheus
        prometheus.io/port: "9001"
    spec:
      # the list of containers in the Pod (one in this case)
      containers:
        # the name of the pod
        - name: catalog-service
          # the image used to run the container. no tag is defined, so "latest" will be used implicitly.
          image: catalog-service
          # instruct k8s to pull the image from a container registry only if it's not present locally yet.
          imagePullPolicy: IfNotPresent
          lifecycle:
            # makes k8s wait 5 seconds before sending the SIGTERM signal to the Pod.
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            # the ports exposed by the container
            - containerPort: 9001
          # the list of environment variables passed to the Pod.
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_PROFILES_ACTIVE
              value: test-data
          # configuration for the liveness probe.
          livenessProbe:
            # uses and HTTP GET request to get the liveness state.
            httpGet:
              # the endpoint to call for the liveness state.
              path: /management/health/liveness
              # the port to use to fetch the liveness state.
              port: 9001
            # and initial delay before starting checking the liveness state.
            initialDelaySeconds: 10
            # the frequency for checking the liveness state.
            periodSeconds: 5
          # configuration for the readiness probe.
          readinessProbe:
            httpGet:
              path: /management/health/readiness
              port: 9001
            initialDelaySeconds: 5
            periodSeconds: 15
          # Mounts the ConfigMap in the container as a volume
          volumeMounts:
            - name: catalog-config-volume
              # Spring Boot will automatically find and include property files from this folder.
              mountPath: /workspace/config
      # Defines volumes for the Pod
      volumes:
        # The name of the volume
        - name: catalog-config-volume
          # The ConfigMap from which to create a volume
          configMap:
            name: catalog-config
