apiVersion: v1
kind: Service
metadata:
  # the name of the Service, it must be a valid DNS name.
  name: catalog-service
  labels:
    # a label attached to the Service.
    app: catalog-service
spec:
  # the type of Service
  type: ClusterIP
  selector:
    # the label used to match the Pods to target and expose
    app: catalog-service
  ports:
    - protocol: TCP
      # the port exposed by the Service
      port: 80
      # the port exposed by the Pods targeted by the Service.
      targetPort: 9001
