apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Uses the manifests in your Catalog Service repo on GitHub as the base for further customizations
  - github.com/sanjayrawat1/bookshop/catalog-service/k8s?ref=main

# Section containing the list of patches to apply to the base manifests according to the strategic merge strategy
patchesStrategicMerge:
  # The patch for customizing the environment variables passed to the Catalog Service container
  - patch-env.yml

configMapGenerator:
  # The same ConfigMap name used in the base Kustomization
  - name: catalog-config
    # Merges this ConfigMap with the one defined in the base Kustomization
    behavior: merge
    files:
      # The additional property file added to the ConfigMap
      - application-staging.yml

images:
  - name: catalog-service
    newName: ghcr.io/sanjayrawat1/catalog-service
    newTag: latest

replicas:
  - name: catalog-service
    count: 2
