apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/sanjayrawat1/bookshop/dispatcher-service/k8s?ref=main

patchesStrategicMerge:
  - patch-env.yml

configMapGenerator:
  - name: dispatcher-config
    behavior: merge
    files:
      - application-staging.yml

images:
  - name: dispatcher-service
    newName: ghcr.io/sanjayrawat1/dispatcher-service
    newTag: latest

replicas:
  - name: dispatcher-service
    count: 1
